// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAeeHBoid1sKPMEwwq0Fs0-Ab5QZOyIcc',
    appId: '1:373372710193:web:88e1f3bfd877da3d2ad410',
    messagingSenderId: '373372710193',
    projectId: 'academic-nexus-db32d',
    authDomain: 'academic-nexus-db32d.firebaseapp.com',
    storageBucket: 'academic-nexus-db32d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ1EO1noz8rKi802TS9QZ3-SFNGdBBTOM',
    appId: '1:373372710193:android:47fcd29ef246f46c2ad410',
    messagingSenderId: '373372710193',
    projectId: 'academic-nexus-db32d',
    storageBucket: 'academic-nexus-db32d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiWFtqqWSAXZvqLnBJ7DIwx0vdBooywPs',
    appId: '1:373372710193:ios:ec8431253306389c2ad410',
    messagingSenderId: '373372710193',
    projectId: 'academic-nexus-db32d',
    storageBucket: 'academic-nexus-db32d.firebasestorage.app',
    iosBundleId: 'com.example.academicNexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiWFtqqWSAXZvqLnBJ7DIwx0vdBooywPs',
    appId: '1:373372710193:ios:ec8431253306389c2ad410',
    messagingSenderId: '373372710193',
    projectId: 'academic-nexus-db32d',
    storageBucket: 'academic-nexus-db32d.firebasestorage.app',
    iosBundleId: 'com.example.academicNexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAeeHBoid1sKPMEwwq0Fs0-Ab5QZOyIcc',
    appId: '1:373372710193:web:5fbdab855d7e9c482ad410',
    messagingSenderId: '373372710193',
    projectId: 'academic-nexus-db32d',
    authDomain: 'academic-nexus-db32d.firebaseapp.com',
    storageBucket: 'academic-nexus-db32d.firebasestorage.app',
  );
}
